# Set up container
container_init_file="/run/container.init"

# If the container hasn't been initialized yet...
if ! [[ -f "${container_init_file}" ]]
then
  # Copy files to home dir if they don't exist
  for x in \
    tmux.conf \
    p10k.zsh
  do
    if ! [[ -f "${HOME}/${x}" ]]
    then
      cp -v "/opt/system-files/${x}" "/${HOME}/.${x}"
    fi
  done

  # Install asdf packages
  while read pkg
  do
    asdf plugin add "${pkg}"
    asdf install "${pkg}" latest
    asdf global "${pkg}" latest
  done < "/opt/system-files/asdf-packages.txt"

  # Create file to show that the container has been initialized
  date > "${container_init_file}"

  if ! [[ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]]
  then
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  fi
fi

ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# tmux
# ZSH_TMUX_AUTOSTART=true
# ZSH_TMUX_AUTOCONNECT=true
# ZSH_TMUX_AUTOQUIT=true
# ZSH_TMUX_CONFIG="/opt/tmux.conf"
# ZSH_TMUX_UNICODE=true

# This needs to be before we source the zsh-syntax-highlighting plugins
autoload -U select-word-style
select-word-style shell

# If command execution time above min. time, plugins will not output time.
ZSH_COMMAND_TIME_MIN_SECONDS=3

# Exclude some commands
ZSH_COMMAND_TIME_EXCLUDE=(vim nvim)

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    colored-man-pages
    python
    sudo
    # tmux
    command-time
    zsh-syntax-highlighting
    zsh-autosuggestions
    fd
    git-extras
    isodate
    jsontools
)

source $ZSH/oh-my-zsh.sh

# User configuration
################################################################################
umask 0077

# Aliases
################################################################################
alias drop_cache='sudo sync && sudo sysctl -w vm.drop_caches=3'
alias drop_swap='sudo sync && sudo sysctl -w vm.drop_caches=3 && sudo swapoff -a && sudo swapon -a'
alias ipcalc='/usr/bin/ipcalc -n'
alias ls='/bin/ls --color -Fh'
alias docker=podman
alias docker-compose=podman-compose
alias bat="batcat"
alias db='distrobox'
alias cat='batcat --paging=never --style plain'
alias ccat='/usr/bin/cat'
alias default_branch='echo "$(basename "$(git symbolic-ref refs/remotes/origin/HEAD --short)")"'
alias current_branch='$(git rev-parse --abbrev-ref HEAD)'
alias fd='fdfind'

# Other
################################################################################
export PIPENV_VENV_IN_PROJECT=1

# Make sure we have the latest and working host-spawn when we start
################################################################################
if [[ -f "/usr/bin/distrobox-host-exec" ]]
then
  /usr/bin/distrobox-host-exec -Y /usr/bin/true
fi

# Set up asdf
. "$HOME/.asdf/asdf.sh"
# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

# PATH
################################################################################
PATH="${HOME}/bin:${PATH}"
PATH="${HOME}/.local/bin:${PATH}"
export PATH
