if [[ -f "/run/.containerenv" ]]
then
  container=1
  export TERM=xterm-256color COLORTERM=truecolor

  # tmux doesn't open in UTF-8 mode in container
  alias tmux='tmux -u'
fi

# Reconnect to detached TMUX sessions
if command -v tmux >/dev/null
then
  if ! [[ "$TMUX" ]]
  then
    if tmux ls | grep -qvw attached
    then
      tmux attach-session
      exit 0
    else
      tmux new-session
      exit 0
    fi
  fi
fi

# Path to oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"


ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the followin line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=14

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# # # Set tmux to auto start
# export ZSH_TMUX_AUTOSTART=true

# # # ZSH_TMUX_AUTOSTART_ONCE=true

# # # Automatically connect to a previous session if it exits
# # export ZSH_TMUX_AUTOCONNECT=true

# # # Set tmux -u option to support unicode
# ZSH_TMUX_UNICODE=true

# # ZSH_TMUX_DETACHED=true

# This needs to be before we source the zsh-syntax-highlighting plugins
autoload -U select-word-style
select-word-style shell

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    colored-man-pages
    python  # IIRC will show the set and show the venv if you wnter a dir with venv
    sudo
    command-time
    zsh-syntax-highlighting
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# Create bin directory if it doesn't exist
[[ -d "${HOME}/bin" ]] || mkdir -p "${HOME}/bin"

# User configuration
################################################################################
export PATH="${HOME}/bin:/var/lib/flatpak/exports/bin:$PATH"
umask 0077

# Pipenv venv in dir needed for vscode and to supress warnings.
export PIPENV_VENV_IN_PROJECT=1 PIPENV_VERBOSITY=1

# Aliases
################################################################################
alias drop_cache='sudo sync && sudo sysctl -w vm.drop_caches=3'
alias drop_swap='sudo sync && sudo sysctl -w vm.drop_caches=3 && sudo swapoff -a && sudo swapon -a'
alias ipcalc='/usr/bin/ipcalc -n'
# alias netstat='sudo /bin/netstat'
alias open='xdg-open'
# alias localenv='virtualenv --prompt "($(basename "$PWD"))" .venv; cd .'
# alias pip='pip3'
# alias whatismyip='dig myip.opendns.com @resolver1.opendns.com +short'
alias ls='/bin/ls --color -Fh'
alias docker=podman
alias docker-compose=podman-compose
# alias microk8s='sudo /snap/bin/microk8s'
# alias kubectl='sudo /snap/bin/microk8s kubectl'
# alias reload='source "${HOME}/.zshrc"'
# alias code='code-insiders'
alias db='distrobox'
alias cat='bat --paging=never --style plain'
alias clean_mem='drop_swap'
alias default_branch='git checkout "$(basename "$(git symbolic-ref refs/remotes/origin/HEAD --short)")"'
alias default_branch_show='echo "$(basename "$(git symbolic-ref refs/remotes/origin/HEAD --short)")"'
alias l='eza -A --icons=always'
alias ll='l -l'
alias code="com.visualstudio.code"
alias vim=nvim

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# PATH="${HOME}/go/bin:$PATH"

# Cause less to not page if there is less than a page of data
export LESS='-F'

export EDITOR=nvim
