---
name: Build and Publish Container Images

on:
  push

env:
  image_name: my-workspace

jobs:
  tags:
    name: Push Tags
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: version
        uses: reecetech/version-increment@2023.9.3
        with:
          scheme: semver
          increment: patch

      - name: Push additional tags
        run: |
          git tag -f "${{ steps.version.outputs.major-v-version }}"
          git tag -f "${{ steps.version.outputs.major-v-version }}.${{ steps.version.outputs.minor-version }}"
          git tag -f "${{ steps.version.outputs.v-version }}"
          git push -f --tags

  build_base_image:
    name: Build Base Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login To Quay.io container registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create container metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/josephtole/my-workspace

          tags: |
            type=raw,value=base

          flavor: |
            latest=false

      - name: Build and push image to registry
        uses: docker/build-push-action@v5
        with:
          context: "{{ defaultContext }}:images/base"
          file: Containerfile
          push: true
          load: false
          labels: ${{ steps.docker-metadata.outputs.labels }}
          tags: ${{ steps.docker-metadata.outputs.tags }}

  build_container_image:
    name: Build Images
    runs-on: ubuntu-22.04
    needs: [tags, build_base_image]

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    strategy:
      matrix:
        environment: [home, work]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login To Quay.io container registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create container metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/josephtole/my-workspace

          tags: |
            type=raw,value=${{ matrix.environment }}

          flavor: |
            latest=false

      - name: Build and push image to registry
        uses: docker/build-push-action@v5
        with:
          context: "{{ defaultContext }}:images/${{ matrix.environment }}"
          file: Containerfile
          push: true
          load: false
          labels: ${{ steps.docker-metadata.outputs.labels }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
